general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = wlopm --on HDMI-A-2
}

listener {
    timeout  = 300
    on-timeout = wlopm --off HDMI-A-2
    on-resume  = wlopm --on HDMI-A-2
}
