bind=SUPER+SHIFT,r,reload_config

bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,Return,spawn,alacritty
bind=SUPER,e,spawn,nautilus
bind=SUPER,b,spawn,~/.config/mango/scripts/browser
# Volume control
bind=NONE,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume up
bind=NONE,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume down
bind=NONE,XF86AudioMute,spawn,~/.config/mango/scripts/volume mute
bind=SUPER,XF86AudioMute,spawn,~/.config/mango/scripts/switch-audio
# External display brightness
bind=SUPER,minus,spawn,ddcutil setvcp 10 - 5
bind=SUPER,equal,spawn,ddcutil setvcp 10 + 5
# Nightlight
bind=SUPER,w,spawn_shell,pgrep wlsunset || wlsunset -T 4500 && pkill wlsunset
# Powermenu
bind=SUPER,p,spawn,~/.config/mango/scripts/powermenu

bind=NONE,Print,spawn, grim -g "$(slurp)" $(xdg-user-dir PICTURES)/Screenshots/$(screenshot_date +'%s_grim.png')

bind=SUPER,m,quit
bind=SUPER,q,killclient,

bind=SUPER,Tab,focusstack,next
# Change focus window
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# Sort of pinned window on every tag
bind=SUPER,g,toggleglobal,
# Overview of all the windows
bind=SUPER,o,toggleoverview,
bind=SUPER+SHIFT,Space,togglefloating,
bind=SUPER,a,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,

# Layouts
bind=SUPER,t,setlayout,tile
bind=SUPER,v,setlayout,vertical_grid
bind=SUPER,c,setlayout,spiral
bind=SUPER,x,setlayout,scroller
bind=SUPER,n,switch_layout

# Tag switching
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# Window movement from tag to tag
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

bind=SUPER+SHIFT,X,incgaps,1
bind=SUPER+SHIFT,Z,incgaps,-1

bind=SUPER+ALT,k,resizewin,+0,-50
bind=SUPER+ALT,j,resizewin,+0,+50
bind=SUPER+ALT,h,resizewin,-50,+0
bind=SUPER+ALT,l,resizewin,+50,+0

mousebind=SUPER,btn_left,moveresize,curmove
# mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
