source=~/.config/mango/window.conf
source=~/.config/mango/animations.conf
source=~/.config/mango/layout.conf
source=~/.config/mango/appearance.conf
source=~/.config/mango/input.conf
source=~/.config/mango/tags.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/autostart.conf
source=~/.config/mango/monitors.conf
