#!/usr/bin/env bash

power_args=$(printf '%b' 'Lock\nLogout\nRestart\nSuspend\nHibernate\nPoweroff' |
  rofi -dmenu -p "" -i -theme-str 'window {width: 10em; padding: 2px; height: 22em;}')

# TODO: lock, logout not working
case "$power_args" in
*Lock)
  # loginctl lock-sessions
  ;;
*Logout)
  ;;
*Restart)
  systemctl reboot
  ;;
*Suspend)
  systemctl suspend
  ;;
*Hibernate)
  systemctl hibernate
  ;;
*Shutdown)
  systemctl poweroff
  ;;
esac
